# codelab 1
a. Buatlah 12 data tuple yang berisi masing-masing 4 data int, float, dan string dengan urutan acak.

b. Ubahlah data tuple tersebut menjadi list.

c. Tambahkan 2 data baru di index sesuai dengan NIM akhir kalian (jika NIM akhir adalah 0, maka index ke-10).

d. Hapus tipe data float pada list.

e. Urutkan elemen pada list secara descending.

In [1]:
# Codelab 1
# a. Buat 12 data tuple dengan masing-masing 4 data int, float, dan string

tuplr = (1, 3, 5, 7, 1.25, 2.25, 3.35, 4.55, "susu", "sapi", "bola", "duduk")

# b. Ubah tuple menjadi list
list_data = list(tuplr)

# c. Tambahkan 2 data baru di index sesuai dengan NIM akhir (karena 3 digit terakhir NIM adalah 298, maka index ke-8)
list_data.insert(8, "kelinci")
list_data.insert(9, "burung")

# d. Hapus tipe data float pada list
list_data = [item for item in list_data if not isinstance(item, float)]

# e. Urutkan elemen pada list secara descending
# Pisahkan data int dan string agar bisa diurutkan masing-masing
int_data = sorted([item for item in list_data if isinstance(item, int)], reverse=True)
str_data = sorted([item for item in list_data if isinstance(item, str)], reverse=True)

# Gabungkan hasil
sorted_list = int_data + str_data

# Output hasil
print(sorted_list)


[7, 5, 3, 1, 'susu', 'sapi', 'kelinci', 'duduk', 'burung', 'bola']


# Codelab 2

a. Buatlah array 2D berdasarkan 6 digit terakhir NIM kalian.

b. Lakukan operasi pertambahan, pengurangan dan perkalian pada matriks yang kalian buat.

c. Ubahlah matriks tersebut menjadi bentuk 1D.

d. Lakukan slicing pada matriks.

In [3]:
import numpy as np

# a. Buat array 2D berdasarkan 6 digit terakhir NIM (311298)
array_2d = np.array([[3, 1, 1], [2, 9, 8]])
print("Array 2D:\n", array_2d)

# b. Lakukan operasi pertambahan, pengurangan, dan perkalian pada matriks
matrix_add = array_2d + array_2d
matrix_sub = array_2d - array_2d
matrix_mul = array_2d * array_2d

print("\nHasil Pertambahan:\n", matrix_add)
print("\nHasil Pengurangan:\n", matrix_sub)
print("\nHasil Perkalian:\n", matrix_mul)

# c. Ubah matriks menjadi bentuk 1D
array_1d = array_2d.flatten()
print("\nArray 1D:\n", array_1d)

# d. Lakukan slicing pada matriks
sliced_array = array_2d[:, 1:]  # Mengambil semua baris, mulai dari kolom ke-1 hingga akhir
print("\nHasil Slicing:\n", sliced_array)


Array 2D:
 [[3 1 1]
 [2 9 8]]

Hasil Pertambahan:
 [[ 6  2  2]
 [ 4 18 16]]

Hasil Pengurangan:
 [[0 0 0]
 [0 0 0]]

Hasil Perkalian:
 [[ 9  1  1]
 [ 4 81 64]]

Array 1D:
 [3 1 1 2 9 8]

Hasil Slicing:
 [[1 1]
 [9 8]]


# Codelab 3
a. Buatlah sebuah series yang berisi dictionary yang memuat nama produk dan ID produk.

b. Buatlah sebuah dataframe yang berisi dictionary yang memuat 4 kolom dan setiap kolom berisi 5 data. Tidak boleh ada kesamaan antar praktikan.

c. Tambahkan 1 kolom baru.

d. Urutkan dataframe, misalnya berdasarkan abjad jika kolom berupa Nama.

In [2]:
import pandas as pd

# a. Buat Series yang berisi dictionary dengan nama produk dan ID produk
produk = {"swallo xxx": 101, "swallo premium": 102, "swallo zeus": 103, "swallo dxd": 104, "swallo brondong": 105}
series_produk = pd.Series(produk)
print("Series Produk:\n", series_produk)

# b. Buat DataFrame dengan 4 kolom dan masing-masing 5 data
data = {
    "Nama": ["Joko", "Ambalabu", "Ambacit", "Sigmatris", "Bambang"],
    "Usia": [23, 30, 21, 35, 29],
    "Kota": ["Jakarta", "Ngawi", "Jombang", "Medan", "Semarang"],
    "Pekerjaan": ["Programmer", "Kang sawer", "Pengangguran", "Manager", "Guru ngaji"]
}
df = pd.DataFrame(data)
print("\nDataFrame Awal:\n", df)

# c. Tambahkan 1 kolom baru (misalnya Gaji)
df["Gaji"] = [7000000, 8000000, 6000000, 10000000, 9000000]
print("\nDataFrame dengan Kolom Gaji:\n", df)

# d. Urutkan DataFrame berdasarkan Nama secara alfabetis
df_sorted = df.sort_values(by="Nama")
print("\nDataFrame Terurut berdasarkan Nama:\n", df_sorted)


Series Produk:
 swallo xxx         101
swallo premium     102
swallo zeus        103
swallo dxd         104
swallo brondong    105
dtype: int64

DataFrame Awal:
         Nama  Usia      Kota     Pekerjaan
0       Joko    23   Jakarta    Programmer
1   Ambalabu    30     Ngawi    Kang sawer
2    Ambacit    21   Jombang  Pengangguran
3  Sigmatris    35     Medan       Manager
4    Bambang    29  Semarang    Guru ngaji

DataFrame dengan Kolom Gaji:
         Nama  Usia      Kota     Pekerjaan      Gaji
0       Joko    23   Jakarta    Programmer   7000000
1   Ambalabu    30     Ngawi    Kang sawer   8000000
2    Ambacit    21   Jombang  Pengangguran   6000000
3  Sigmatris    35     Medan       Manager  10000000
4    Bambang    29  Semarang    Guru ngaji   9000000

DataFrame Terurut berdasarkan Nama:
         Nama  Usia      Kota     Pekerjaan      Gaji
2    Ambacit    21   Jombang  Pengangguran   6000000
1   Ambalabu    30     Ngawi    Kang sawer   8000000
4    Bambang    29  Semarang    Gu